### ISSUE TITLE
Hello, may I know how to quickly change and configure the interface address

### ISSUE THREAD

**Issue by RyanHo97** [tangllty/tang-vue#1]
I tried this：
![image](https://github.com/tangllty/tang-vue/assets/49436413/4418ea3d-a2d3-423c-84b3-6ce3584cddea)
But the request was still made at the original address
![image](https://github.com/tangllty/tang-vue/assets/49436413/0c8a73a3-19ac-4930-90a4-3e049a221404)

**Comment by tangllty** [comment]
Hi, what is your expected outcome.

**Comment by RyanHo97** [comment]
> Hi, what is your expected outcome.

Thank you for your reply
**I want to be able to log in**
I deployed tang-boot on the server, but now there is an error logging in. Is there a problem with my interface address configuration

![3695d43dffd57744297f7babc5214fc](https://github.com/tangllty/tang-vue/assets/49436413/8a819ef4-e330-4bcf-86a4-03778f9a3410)

**Comment by tangllty** [comment]
> > Hi, what is your expected outcome.
> 
> Thank you for your reply **I want to be able to log in** I deployed tang-boot on the server, but now there is an error logging in. Is there a problem with my interface address configuration
> 
> ![3695d43dffd57744297f7babc5214fc](https://user-images.githubusercontent.com/49436413/246041264-8a819ef4-e330-4bcf-86a4-03778f9a3410.png)

Hi, your configuration is correct, the issue is because ip2region.xdb was not found, I have fixed this issue, you can pull the latest code to fix it.

**Comment by RyanHo97** [comment]
Thank you very much, my backend is not the latest
If you have any future needs, I am willing to co build the front-end part with you

**Comment by tangllty** [comment]
> 

I appreciative that, my front-end is not good. I have problems a lot. Should I create a group or something?

**Comment by RyanHo97** [comment]
> > 
> 
> I appreciative that, my front-end is not good. I have problems a lot. Should I create a group or something?



Of course, I am also constantly learning
This is my WeChat account: at-WZM521

**Comment by tangllty** [comment]
> 

I sent a friend request
